__author__ = 'Victor'
#Victor Trujillo
#Ecen 303 - Chamberland Spring 2015
#Due 5/1/15
#Challenge4.py
import random

NumberTrials = 1000
sequenceX=[]
sequenceY=[]
sequenceZ=[]

for TrialIndex in range(0, NumberTrials):
	sequenceX.append(random.randint(1,6))
	if sequenceX[TrialIndex] == 1 or sequenceX[TrialIndex] == 3 or sequenceX[TrialIndex] ==5:
		sequenceY.append(random.randint(1,6))
	else:
		sequenceY.append(0)
	sequenceZ.append(sequenceX[TrialIndex]+sequenceY[TrialIndex])

percent = []
for OutcomeIndex in range (2,12):
	percent.append(sequenceZ.count(OutcomeIndex)/ float(NumberTrials))
print("The following code displays the probabilities generated by the given code")
print(percent)
print '\n'
print("The following list are Z(X+Y) and the its corresponding probabilities calculated by hand")
Result = [2,3,4,6,7,8,9,10,11]
Probabilities = [7.0/36,1.0/36,8.0/36,2.0/36,9.0/36,3.0/36,2.0/36,2.0/36,1.0/36,1.0/36]
RoundedProb = ['%.3f' % elem for elem in Probabilities]
print (Result)
print (RoundedProb)
print("When Z = 4, the probability is 8/36 = .222.")
print("The more trials that are done (N) the closer the probability converges to this value ")
